### ISSUE TITLE
normaliser le nom des docker du backend

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#1]
Proposition :

Pour s'aligner avec deces-ui, et avoir une lecture harmonieuse sur le docker hub des images dockers du projet matchid :

matchid/deces-backend-development:${APP_VERSION} (pour le dev, actuellement : deces-backend-backend-developpement)

matchid/deces-backend:${APP_VERSION} (pour les images compilées, faites pour des déploiement que ce soient de la preprod ou de la production)

une deuxième issue doit être créée pour nginx, mais dans le repo unique avec submodules dès qu'il sera créé

**Comment by cristianpb** [comment]
I changed backend image names as proposed: 

* deces-backend-development:${APP_VERSION}
* deces-backend:${APP_VERSION}

I used git tags as ${APP_VERSION}. Starting from v0.

Related commit: e04012fae161ef536eac7e2f089571ed7722d051

**Comment by rhanka** [comment]
Comme indiqué ci-dessus, il y a l'identifiant docker hub à mettre devant pour pouvoir pousser l'image avec un docker push et la tirer avec un pull. il faudrait que ce soit plutôt:
-  ${DOCKER_USERNAME}/deces-backend-development:${APP_VERSION}
- ${DOCKER_USERNAME}/deces-backend:${APP_VERSION}

ce paramètre sera réutilisable sur une registry privée le cas échéant, et fonction aussi en local.

**Comment by rhanka** [comment]
validé ici e04012fae161ef536eac7e2f089571ed7722d051
