### ISSUE TITLE
gérer les erreurs de dispo elasticsearch et les erreurs de formattage de requête

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#10]
dans "runRequest.ts" (conçu pour un appel front => nginx) le statut devrait remonter de façon explicite dans le cas (back => es) : 
- erreurs 500 : erreur non maîtrisée interne ou erreur elasticsearch (500 si erreur ES)
- erreurs 400 : si erreur de parsing de la query (pb de type etc),

Erreurs de charge: voir si l'on retoure un 429 (régulation) en cas d'erreur 502 d'elastisearch (déni de service si temporaire) ou si l'on reporte le 502. Normalement le 502 ne devrait être reporté par nginx que si le backend lui-même est en défaut.

**Comment by rhanka** [comment]
à voir si erreur 500 ES avec la requête suivante : 
'{"fuzzy":"true","sort":[{"score":"desc"}],"page":1,"size":20,"lastName":"inconnu"}'

**Comment by cristianpb** [comment]
Done in #162
