### ISSUE TITLE
stabiliser le format de la donnée de réponse

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#11]
il faut choisir entre : 
- conserver la réponse brute elasticsearch - et donc supprimer "msg" qui ajoute une incompatibilité inutile avec les parseurs standards de réponse ES
- parser la réponse elasticsearch directement dans le backend pour éviter la hiérarchie un peu lourde du json d'elasticsearch (choix fait sur histovec) - cette option est un peu plus popre mais nécessite un peu de dev

L'option retenue devrait être définitive avant un premier passage en prod afin d'éviter de développer deux fois le parsing des réponses entre font et back.

**Comment by rhanka** [comment]
proposition Hassan:
```
{
    "query" : "dupont henri 1920",
    "limit": "10",
    "dcd" : [
            {"nom" : "dupont",
            "prenom": "henri",
            "date_de_naissance":"10/12/1920",
            "date_de_deces":"01/01/2000",
            "lieu_de_naissance": "PARIS",
            "score":"100"
            },.....
    ]
}
```

Plusieurs questions :
- renommer les champs front/back ? (proposition : non)
- renommer les champs elasticsearch ? (proposition : non, mais dans la réponse utiliser les champs front)
- rappeler la query ? pourquoi pas
- le champ "dcd" est pas beau du tout (proposition : response.deaths, avec response.total, response.size et response.page

**Comment by mogador26** [comment]
Oui je confirme. 
Du coup name, first_name, sex sont au niveau se trouve au même niveau que date.
Dans la réponse  il faudrait que l'on rajoute le max_score. Et le score est rattaché à chaque identité.
