### ISSUE TITLE
intégrer les queries avancées disponibles sur le frontend

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#2]
selon

src/components/tools/quieries.js du frontend (=> remplacer une partie du contenu de src/types/queries.ts qui suit le même esprit)

manquent les fonctions :
- recherche par plage de date (naissance, décès)
- recherche par commune, département (naissance, décès)
- recherche par prénom
- activation/désactivation de la recherche stricte

A première vue le schéma swagger peut être respecté, et juste complété.

A discuter néanmoins le remplacement (réalisé dans le frontend) ou pas d'une query simple (dateRangeString) par 2 ou 4 queries, puisque les fonctions assurées par une seule fonction est:
- 1970: recherche par année
- 01/02/1970: recherche par date
- 1970-1980: recherche par plage d'années
- 01/02/1970-05/01/1971: recherche par plage de dates

Je propose de prendre en charge, mais vous laisse la main le cas échéant

**Comment by cristianpb** [comment]
Le commit c39e9736601215050f9eecaff219cfc39a0ecd15 les champs de recherche avancée par dateRange. Le fonctionnement est le même que celui du frontend. 

birthDate: peut être interrogé sur les 3 formes "1910-1912 ou 1911 ou 05/07/1911". Ce qui est un peu doublon avec birthYear. 

De la même façon, je pense que deathDate et deathYear peuvent être combinés. 

Il manque à intégrer l'activation/désactivation de la recherche stricte.

**Comment by rhanka** [comment]
Effectivement, birthYear et deatYear ne sont plus utilisés sur le front et sont totalement inutiles

**Comment by cristianpb** [comment]
J'ai enlevé les paramètres deathYear et birthYear ici: 795dfd05e69da72f14db12c84f2cb9f853f4109a

J'ai intégré l'activation/désactivation de la recherche stricte ici: 44a8aef87793569ffe25c747dc8ca04cbc2181ef

**Comment by rhanka** [comment]
Il reste à gérer la fonction de "sort", qui ne fonctionne plus avec le backend
Celle-ci n'aboutissait pas à un statut dans l'URL, du coup tu l'as peut être manquée.

Validé en mode POST : 
- dates (birth, death, par date et plage)
- fuzzy (auto ou false)
- autres champs

**Comment by rhanka** [comment]
Je clos cette issue, et en crée une autre pour le sort, qui est un peu spécifique
