### ISSUE TITLE
Allow search by geolocation

### ISSUE THREAD

**Issue by DoneDeal0** [matchID-project/deces-backend#309]
Bonjour,

Bravo pour votre travail. Il est aujourd'hui possible de faire une recherche précise par ville ou code postal, mais serait-il également possible d'ajouter une recherche par geolocation?

Cas d'usage: dans une grande métropole, le nombre de résultats peut être énorme. Limiter la recherche à un radius précis pourrait apporter plus de précision. 

Exemple d'usage:

```js
// retourne les résultats à 3km autour des coordonnées [-1.34, 41.10]
"https://deces.matchid.io/deces/api/v1/search?latitude=41.10&longitude=-1.34&maxDistance=3")
```
Il me semble qu'il existe un point `GEOPOINT_DECES` dans votre cluster Elastic Search (cf [/buildRequest.ts](https://github.com/matchID-project/deces-backend/blob/07f5d62ace3bce37e01fad1add3502918e67398a/backend/src/buildRequest.ts#L484) ). Comme les données de geolocation sont fournies dans les réponses, je pense que ça peut être envisageable.

**Comment by rhanka** [comment]
Bonjour ! 
Merci pour cette demande
Dans l'absolu, ce n'est pas une requête si simple.
Le GEOPOINT_DECES correspond au barycentre de la commune. Du coup lorsqu'on demande les décès à 3km, p.ex un point entre deux communes dont les centres sont distants de plus de 3km, la réponse sera 0, même si le décès a eu lieu dans l'une des deux communes.

Nous utilisons cette donnée uniquement pour calculer la vraisemblance du score géographique (e.g lorsque la commune n'est pas la bonne mais est voisine à peu de km, on dégrade un peu le score mais pas trop).

La bonne réponse à votre demande serait apportée par une indexation du contour geojson de la commune, et une requête de type point / contour. Ce qui est faisable (avec une petite imprécision mais acceptable) avec elasticsearch. 
Ajouter le geocontour commune à chaque décès multiplierai la taille de la base par un facteur 10 à 100 (au doigt mouillé), donc c'est à éviter, parce qu'un geojson c'est gros. Je ne pense pas que ça vaille la peine.

L'autre solution est qu'au moment de la requête on fasse la requête sur une api comme https://geo.api.gouv.fr/decoupage-administratif/communes#geo pour, à partir d'une recherche geographique, recueillir la liste des communes et faire plutôt la recherche sur une liste de commune : coordonnées gps + distance = ensemble de communes possibles. En cas de besoin "haute performances" sur ce besoin, il nous faudrait ajouter un indexe des geojson des communes pour éviter un tiers appel API.

Quel est votre cas d'usage ? forcément, selon la potentialité de réutilisation cela nous motivera :-)

**Comment by DoneDeal0** [comment]
Bonjour,

En observant la réponse de l’API, je me suis aperçu que les objets dans l’array `response.persons` avaient une clef `death.location.latitude `et `death.location.longitude`. Ces données sont rigoureusement exactes, à la rue près. 

Je pensais donc que l’on pouvait facilement indexer ces deux champs et autoriser une recherche par géolocation. De mon point de vue il n’y a pas besoin de considérer la notion de commune. Chaque coordonnée serait indépendante et indexée sur une sphere 2D. Cela dit, je n’ai fait de la geolocation qu’avec MongoDB, je n’ai aucune connaissance sur Elastic Search, d’où ma proposition peut-être naïve. 

Il y aurait beaucoup de cas d’usages possibles (historiques, immobiliers, etc.) avec une telle option de recherche. De plus les résultats reçus actuellement bénéficieraient d’un filtrage optionnel beaucoup plus précis.

**Comment by cristianpb** [comment]
Bonjour @DoneDeal0

Vous pouvez déjà faire des requêtes en utilisant un point de géolocalisation pour le lieu de naissance et de décès. Par exemple la requête suivante retourne les résultats pour les personnes nées à 10km autour des coordonnées [2.98, 49.6]:

```bash
curl -X 'POST' \
  'https://deces.matchid.io/deces/api/v1/search' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "firstName": "jean",
  "sex": "M",
  "birthGeoPoint": {"latitude": 49.6, "longitude": 2.98, "distance": "10km"}
}'
```

Cette commande fonctionne actuellement uniquement en mode POST. Vous pouvez trouver plus d'information dans [la documentation de l'API](https://deces.matchid.io/deces/api/v1/docs/#/).

**Comment by DoneDeal0** [comment]
Bonjour @cristianpb , merci beaucoup pour votre réponse! En effet, ça répond à ma question. Néanmoins, je ne parviens pas à effectuer un curl valide en utilisant la clef `deathGeoPoint` (spécifiée dans la documentation), alors que `birthGeoPoint` fonctionne:

```js
curl -X 'POST' \
  'https://deces.matchid.io/deces/api/v1/search' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  “deathGeoPoint": {"latitude": 49.6, "longitude": 2.98, "distance": "10km"}
}'
```

Cela renvoie l'erreur `error - bad JSON formating%`. 

Par ailleurs, en effectuant une requête avec `birthGeoPoint` via axios, celle-ci devient invalide. J'ai pourtant l'impression de l'écrire correctement?

```js
axios
      .post(
        "https://deces.matchid.io/deces/api/v1/search",
        {
          birthGeoPoint: { 
            latitude: 49.6, 
            longitude: 2.98, 
            distance: "10km" 
          }
        },
        {
          headers: {
            accept: "application/json",
            "Content-Type": "application/json"
          }
        }
      )
      .then((res) => console.log("res", res))
      .catch((err) => console.error("err", err));
```

**Comment by cristianpb** [comment]
Pour le curl, il faut utiliser la ligne suivante:
```
+  "deathGeoPoint": {"latitude": 49.6, "longitude": 2.98, "distance": "10km"}
-  “deathGeoPoint": {"latitude": 49.6, "longitude": 2.98, "distance": "10km"}
```

(la difference est dans “)

**Comment by DoneDeal0** [comment]
Bien vu! Désolé pour cette erreur de formatage typique... C'est ok pour la clef `deathGeoPoint` avec un curl, par contre ça coince toujours avec le call axios. J'ai fait une sandbox rapide pour démontrer le souci: https://codesandbox.io/s/exciting-jennings-5puui?file=/src/App.js . Idem un appel fetch simple https://codesandbox.io/s/fetch-post-forked-6el2hn . Sauriez-vous d'où vient le souci dans mon appel?

**Comment by cristianpb** [comment]
@DoneDeal0 
L'erreur du réseau c'est parce qu'il y a une contrainte de sécurité au niveau des appelles POST à partir du navigateur, mais maintenant on peut faire la même requête en utilisant la méthode GET. C'est un peu moche en mode url, par exemple: 

```
https://deces.matchid.io/deces/api/v1/search?birthGeoPoint=%7B%22latitude%22%3A%2049.6%2C%20%22longitude%22%3A%202.98%2C%20%22distance%22%3A%20%2210km%22%7D
```

mais on peut utiliser tu javascript pour rendre ça un peut mieux, par exemple voici un [REPL en svelte](https://svelte.dev/repl/ac2e66261738409db9e3cb763005df53?version=3.46.4)

Il semble que ça répond à la question donc je vais fermer l'issue.

**Comment by DoneDeal0** [comment]
Je confirme que ça fonctionne 👍! Merci!

**Comment by DoneDeal0** [comment]
Hello,

Je vous partage la petite app que j'ai fait avec votre API: https://recherche-personnes-decedees.netlify.app/ . Comme sur votre site, il y a des options de recherches, mais surtout une carte interactive avec des clusters pour mieux visualiser les données. 

<img width="606" alt="Capture d’écran 2022-03-23 à 21 03 15" src="https://user-images.githubusercontent.com/43271780/159786562-6906987f-6ded-4a8b-a9bc-205f2ea93601.png">
<img width="606" alt="Capture d’écran 2022-03-23 à 21 03 59" src="https://user-images.githubusercontent.com/43271780/159786574-f3342c2f-e9ae-4abc-87fb-21d5f925d2db.png">
<img width="605" alt="Capture d’écran 2022-03-23 à 21 05 25" src="https://user-images.githubusercontent.com/43271780/159786576-99ac4b8e-33ab-420f-bd4e-1319b3d9d283.png">

Je vous ai bien entendu cité avec un lien vers le site de matchID.

**Comment by cristianpb** [comment]
Bravo @DoneDeal0 ! :clap:
