### ISSUE TITLE
Ajouter les fonctions d'aggrégation

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#35]
buckets d'aggrégation utiles:
- nom (en tant que terme plutôt que mot clé), prénom (premier prénom)
- histogramme (naissance / décès : par jour semaine mois année)
- départements, communes (terme ou code INSEE), pays
- géo (à voir)

**Comment by cristianpb** [comment]
j'ai quelques questions:
1. ils doivent être facultatives, non ?
2. il faut une nouvelle route pour les agrégations ? `/aggs` ? 
2.1 je pense qu'il faut garder la plus part des paramètres du search. 
3. C'est quoi le format pour la réponse ? 
3.1 Est-ce qu'il faut garder le format ES:

{
  PAYS_NAISSANCE: {
    doc_count_error_upper_bound: 0,
    sum_other_doc_count: 0,
    buckets: [{
                    "key" : "France",
                    "doc_count" : 6
                },
                {
                    "key" : "Espagne",
                    "doc_count" : 3
                },
                {
                    "key" : "Allemagne",
                    "doc_count" : 2
                }]
  }
}
