### ISSUE TITLE
Impossible de renouveler le JWT

### ISSUE THREAD

**Issue by Balsakup** [matchID-project/deces-backend#374]
Lors de l'appel de l'URL `https://deces.matchid.io/deces/api/v1/auth?refresh=true` avec un JWT expiré, mais normalement renouvelable, une erreur est retournée avec le message `{"message":"jwt expired"}`.

Le middleware bloque la requête avant - https://github.com/matchID-project/deces-backend/blob/dev/backend/src/controllers/auth.controller.ts#L102

**Comment by cristianpb** [comment]
Un token a une durée une validité de 1 mois, pendant cette durée, on peut l'utiliser pour s'authentifier et pour faire un renouvèlement (obtenir un nouveau token).

C'est normal que l'on puisse pas utiliser un token de plus d'un mois pour faire un renouvèlement. Il faut passer par l'authentification par email pour obtenir un nouveau token.

**Comment by Balsakup** [comment]
D'accord, merci pour les précisions @cristianpb, j'ai du mal interpréter le code du contrôleur en lisant cette partie là https://github.com/matchID-project/deces-backend/blob/dev/backend/src/controllers/auth.controller.ts#L114-L129
