### ISSUE TITLE
passer de /api/v0 à /deces/api/v1 pour s'harmoniser avec deces-ui

### ISSUE THREAD

**Issue by cristianpb** [matchID-project/deces-backend#6]
le but c'est d'avoir une adresse comme: `http://host/deces/api/v0/search`

il faut se rappeler de modifier le nginx du deces-ui aussi pour prendre en compte le changement

**Comment by rhanka** [comment]
en profiter pour basculer à `deces/api/v1/search` (désolé de ce retour arrière sur v1, mea culpa, mais ma remarque sur la v1 concernait surtout le versionning npm)

Cela permettrait de gérer dans **deces-ui** un mode avec les deux chemins en parallèle : 
-  `deces/api/v0/search` = accès direct ES
-  `deces/api/v1/search` = accès backend

Cela permettra en effet de faire de l'AB testing avec les utilisateurs (le cas échéant ne pas générer directement un rejet massif si on se plante dans la transition)

**Comment by cristianpb** [comment]
bonne idée!

j'ai modifié l'endpoint du backend à `deces/api/v1/search` ici d8ff0ff2d9dd3fbe21bb8c5ad7c2394b7bf10c54

J'ai profité pour faire la monté de version de v0 à v1 et modifier BACKEND_DEV_HOST à BACKEND_DEV

J'ai fait une PR pour adapter deces-ui https://github.com/matchID-project/deces-ui/pull/113

**Comment by rhanka** [comment]
ok ! merci j'ai bien vu ta PR, du coup j'ai fait le travail en double en gérant par ailleurs le tri que tu as implémenté ...
anyway pour cette issue ça me semble bon !
