### ISSUE TITLE
handle "sort" with fields as in deces-ui

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#9]
in deces-ui, there is a drop-down menu used for enabling custom sort.
this sort is given to elasticsearch and disappear in backend

the request should be possible at least in the "post" version of the API.
a parameter coud be : 
{sort: [{"firstName": "desc", "_score": "asc"}]}

the same model as used in elasticearch and deces-ui seem could be simply ported

**Comment by cristianpb** [comment]
The implementation of the sort parameter has been made here: e34498b677c36e7b61bbae656ed10d60f68671a4

It's only available on the POST version. The parameter should look like:
```js
{"sort": [{"firstName": "asc"}, {"score": "asc"}, {"deathCity": "desc"}]}
```

**Comment by rhanka** [comment]
nickel, intégré dans le frontend ici : https://github.com/matchID-project/deces-ui/commit/a5adf6d53214941eb9b2935d732bda9463f5745d
